apiVersion: v1
kind: Pod
metadata:
  name: spring-boot-app-pod

spec:
  containers:
    - name: spring-boot-app-container
      image: ram1uj/spring-boot-app
      ports:
        - containerPort: 5000